config/routes.rb
Rails.application.routes.draw do
  get 'allowed_accounts/new'

  get 'allowed_accounts/create'

  get 'allowed_accounts/destroy'

  get   '/login', :to => 'sessions#new', :as => :login
  get   '/logout', :to => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]

  resources :help_requests, except: [:destroy] do
    put 'resolve', on: :member
  end

  resources :users, only: [:index, :show] do
    get :repos, on: :member
  end
  resources :allowed_accounts, only: [:new, :create, :destroy]

  root 'help_requests#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations do
    def create_from_auth_hash(auth_hash)
      token = auth_hash["credentials"]["token"] if auth_hash["credentials"]

      self.create(:uid => auth_hash["uid"],
                  :provider => auth_hash["provider"],
                  :token => token)
    end
  end
  has_many :help_requests
  has_one :allowed_account, :foreign_key => "github", :primary_key => "github"

  validates :name, :email, :presence => true

  def add_provider(auth_hash)
    # Check if the provider already exists, so we don't add it twice
    unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      authorizations.create_from_auth_hash(auth_hash)
    end
  end

  def authorized?
    allowed_account.present?
  end

  def github_access_token
    gh_auth = authorizations.find_by_provider("github")
    gh_auth.token if gh_auth
  end

  def github_token
    return @gh_token if @gh_token

    if github_access_token
      gh_client = OAuth2::Client.new(Rails.application.secrets.github_key,
                                  Rails.application.secrets.github_secret,
                                  :site => "https://api.github.com")
      @gh_token = OAuth2::AccessToken.new(gh_client, github_access_token)
    end
    @gh_token
  end

  def github_repos
    github_token.get("/user/repos").parsed if github_token
  end

  def to_s
    "#{name} <#{email}>"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, :except => :index
  def index
    @users = User.order(:name)
  end

  def show
  end

  def repos
    @github_repos = @user.github_repos || []
    render :json => @github_repos
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<% content_for :top_bar_left do %>
  <li>
    <%= link_to "New allowed user", new_allowed_account_path %>
  </li>
<% end %>

<h1>Users</h1>

<div class="row">
  <div class="large-12 columns" id="users">
    <table id="users-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Github</th>
          <th>Teacher?</th>
          <th>Authorized?</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr id="<%= dom_id user %>">
            <td><%= link_to user, user %></td>
            <td><%= user.email %></td>
            <td><%= link_to user.github, "https://github.com/#{user.github}" %></td>
            <td><%= user.teacher? %></td>
            <td><%= user.authorized? %></td>
            <td>
              <ul class="button-group radius no-margin">
                <li><%= link_to 'View', user, class: "button tiny" %></li>
              </ul>
  
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user %></h1>

<div class="row">
  <div class="large-12 columns">
    <dl>
      <dt>Name</dt>
      <dd><%= @user.name %></dd>

      <dt>Email</dt>
      <dd><%= mail_to @user.email %></dd>

      <dt>GitHub</dt>
      <dd><%= link_to @user.github, "https://github.com/#{@user.github}" %></dd>

      <dt>Teacher?</dt>
      <dd><%= @user.teacher? %></dd>

      <dt>Authorized?</dt>
      <dd><%= @user.authorized? %></dd>
    </dl>
  </div>

  <div class="large-7 columns">
    <h2>Help Requests</h2>
    <%= render :partial => "help_requests/help_requests", :object => @user.help_requests.unresolved %>
  </div>

  <div class="large-5 columns">
    <h2>GitHub Repos</h2>

    <div id="github-repos" data-user="<%= @user.id %>">
      Loading...
    </div>
  </div>
</div>