config/routes.rb
Rails.application.routes.draw do
  get 'allowed_accounts/new'

  get 'allowed_accounts/create'

  get 'allowed_accounts/destroy'

  get   '/login', :to => 'sessions#new', :as => :login
  get   '/logout', :to => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]

  resources :help_requests, except: [:destroy] do
    put 'resolve', on: :member
  end

  resources :users, only: [:index, :show] do
    get :repos, on: :member
  end
  resources :allowed_accounts, only: [:new, :create, :destroy]

  root 'help_requests#index'

end

app/models/help_request.rb
class HelpRequest < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true
  validates :nature, presence: true
  validates :attempted, presence: true

  scope :unresolved, -> { where("resolved_at IS NULL").order(created_at: :asc) }
  scope :resolved, -> { where("resolved_at IS NOT NULL").order(resolved_at: :desc) }

  def user_name
    user.try(:name)
  end

  def resolve!
    self.resolved_at = Time.zone.now
    save unless new_record?
  end

  def resolved?
    resolved_at.present?
  end

  def can_edit?(user)
    user == self.user
  end

  def can_resolve?(user)
    !resolved? && (can_edit?(user) || user.teacher?)
  end

  def late?
    created_at < Time.zone.now - 1.day
  end
end

app/controllers/help_requests_controller.rb
class HelpRequestsController < ApplicationController
  before_action :require_login
  before_action :set_help_request, only: [:show, :edit, :update, :resolve]
  before_action :require_edit, only: [:edit, :update]
  before_action :require_resolve, only: [:resolve]


  # GET /help_requests
  # GET /help_requests.json
  def index
    @help_requests = HelpRequest.unresolved.includes(:user)
  end

  # GET /help_requests/1
  # GET /help_requests/1.json
  def show
  end

  # GET /help_requests/new
  def new
    @help_request = current_user.help_requests.build
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /help_requests/1/edit
  def edit
  end

  # POST /help_requests
  # POST /help_requests.json
  def create
    @help_request = current_user.help_requests.build(help_request_params)

    respond_to do |format|
      if @help_request.save
        format.html { redirect_to help_requests_path, notice: 'Help request was successfully created.' }
        format.js do
          @help_requests = HelpRequest.unresolved.includes(:user)
          render :create
        end
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /help_requests/1
  # PATCH/PUT /help_requests/1.json
  def update
    if @help_request.update(help_request_params)
      redirect_to help_requests_path, notice: 'Help request was successfully updated.'
    else
      render :edit
    end
  end

  def resolve
    respond_to do |format|
      @help_request.resolve!
      format.html { redirect_to help_requests_path }
      format.js do
        @help_requests = HelpRequest.unresolved.includes(:user)
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_help_request
    @help_request = HelpRequest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def help_request_params
    params.require(:help_request).permit(:repo, :nature, :attempted, :resolved_at)
  end

  def require_edit
    unless @help_request.can_edit?(current_user)
      redirect_to :login, alert: "You do not have permissions to do that."
    end
  end

  def require_resolve
    unless @help_request.can_resolve?(current_user)
      redirect_to :login, alert: "You do not have permissions to do that."
    end
  end
end

app/views/help_requests/_form.html.erb
<%= simple_form_for(@help_request) do |f| %>
  <%= f.error_notification %>

  <%= f.input :repo, label: "What GitHub repo are you having the issue with?" %>
  <%= f.input :nature, label: "What is the nature of your problem?", input_html: {rows: 10} %>
  <%= f.input :attempted, label: "What have you already attempted?", input_html: {rows: 10} %>
  <%= f.button :submit %>
<% end %>

app/views/help_requests/_help_request.html.erb
<tr id="<%= dom_id help_request %>" class="<%= "late" if help_request.late? %>">
  <td><%= link_to_unless_current help_request.user, help_request.user %></td>
  <td>
    <time class="timeago" datetime="<%= help_request.created_at.to_s(:iso8601) %>">
      <%= elapsed_time(help_request.created_at) %>
    </time>
  </td>
  <td>
    <ul class="button-group radius no-margin">
      <% if help_request.can_resolve?(current_user) %>
        <li><%= link_to "Resolve", resolve_help_request_path(help_request), class: "button tiny alert",
                        method: :put, remote: true %></li>
      <% end %>
      <% if help_request.can_edit?(current_user) %>
        <li><%= link_to 'Edit', edit_help_request_path(help_request), class: "button tiny" %></li>
      <% end %>
      <li><%= link_to 'View', help_request, class: "button tiny" %></li>
    </ul>

  </td>
</tr>

app/views/help_requests/_help_requests.html.erb
<% if help_requests.empty? %>
  <p>There are no current help requests. Good job!</p>
<% else %>
  <table id="help-requests-table">
    <thead>
      <tr>
        <th>User</th>
        <th>Time elapsed</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <%= render collection: help_requests, partial: "help_requests/help_request" %>
    </tbody>
  </table>
<% end %>

app/views/help_requests/create.js.erb
$("#new-help-request-modal").
    html('').
    foundation("reveal", "close");

$("#help-requests").html('<%= j render(:partial => "help_requests", :object => @help_requests) %>');
$('#help-request-count').html(<%= @help_requests.count %>);
$('time.timeago').timeago()

app/views/help_requests/edit.html.erb
<h1>Editing help_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @help_request %> |
<%= link_to 'Back', help_requests_path %>

app/views/help_requests/index.html.erb
<% content_for :top_bar_left do %>
  <li>
    <%= link_to "New request", new_help_request_path %>
  </li>
<% end %>

<h1>Outstanding help requests (<span id="help-request-count"><%= @help_requests.count %></span>)</h1>

<div class="row">
  <div class="large-3 large-push-9 columns">
    <%= link_to 'New Help request', new_help_request_path, class: "button radius", remote: true %>
    <div id="new-help-request-modal" class="reveal-modal" data-reveal></div>
  </div>

  <div class="large-9 large-pull-3 columns" id="help-requests">
    <%= render :partial => "help_requests", :locals => {:help_requests => @help_requests} %>
  </div>
</div>

app/views/help_requests/new.html.erb
<div class="small-12 columns">
  <h1>New help request</h1>

  <%= render 'form' %>

  <%= link_to 'Back', help_requests_path %>

</div>

app/views/help_requests/new.js.erb
$("#new-help-request-modal").
    html('<%= j render "form" %>').
    append('<a class=\"close-reveal-modal\">&#215;</a>').
    foundation("reveal", "open");

$("#new_help_request").
      attr("data-remote", "true");

var $helpRequestRepo = $("#help_request_repo");
if ($helpRequestRepo.length > 0) {
    selectRepositories(currentUserInfo().github, $helpRequestRepo);
}

app/views/help_requests/resolve.js.erb
// fade out the completed request
var helpRequestCount = <%= @help_requests.count %>;

$('#<%= dom_id @help_request %>').fadeOut();
$('#help-request-count').html(helpRequestCount);

if (helpRequestCount === 0) {
  $("#help-requests-table").replaceWith("<p>There are no current help requests. Good job!</p>");
}

app/views/help_requests/show.html.erb
<% content_for :top_bar_left do %>
  <li><%= link_to "All requests", help_requests_path %></li>
<% end %>

<p>
<ul class="button-group radius">
  <% if @help_request.can_resolve?(current_user) %>
    <li><%= link_to "Resolve", resolve_help_request_path(@help_request), class: "button small alert", method: :put, data: {confirm: 'Are you sure?'} %></li>
  <% end %>
  <% if @help_request.can_edit?(current_user) %>
    <li><%= link_to 'Edit', edit_help_request_path(@help_request), class: "button small" %></li>
  <% end %>
  <li><%= link_to 'Back', help_requests_path, class: "button small" %></li>
</ul>
</p>

<dl>
  <dt>User</dt>
  <dd><%= link_to @help_request.user, @help_request.user %></dd>

  <% if @help_request.repo? %>
    <dt>Repo</dt>
    <dd><%= link_to @help_request.repo, @help_request.repo %></dd>
  <% end %>

  <dt>Nature</dt>
  <dd><%= simple_format @help_request.nature %></dd>

  <dt>Attempted</dt>
  <dd><%= simple_format @help_request.attempted %></dd>

  <% if @help_request.resolved? %>
    <dt>Resolved at</dt>
    <dd><%= @help_request.resolved_at %></dd>
  <% end %>
</dl>